### ISSUE TITLE
Custom local covers are not loaded

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#178]
### Steps to reproduce

Insert a local file URL in the thumbnail URL text box

### Expected behavior

The image is loaded, like in latest SY preview

![Image SY](https://i.imgur.com/rgDIXSN.png)

### Actual behavior

The image is not loaded

![Image Komikku](https://i.imgur.com/wYUesQI.png)

### Komikku version

r9124

### Android version

Android 12/13

### Device

OnePlus 5T, Lenovo Tab

### Other details

This feature is essential for me because I like to customize the covers and with that I can both have a local backup of the covers and also have them referenced in the entries, so that after a backup restore the covers will all be available again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
How come I can't try set local cover on SY? How to do that?

**Comment by cuong-tran** [comment]
You need to turn on "Files & media" permission:
`App Info -> Permissions -> Files and media"

**Comment by fellinir** [comment]
> You need to turn on "Files & media" permission: `App Info -> Permissions -> Files and media`

@cuong-tran For both SY
![Screenshot_20240722-211039_Permission controller](https://github.com/user-attachments/assets/4df7d191-e271-4715-99fb-3f3c35e5300f)
and Komikku
![Screenshot_20240722-211057_Permission controller](https://github.com/user-attachments/assets/492c1824-e124-4763-a681-85ba5cf9a46e)
There is no `File and Media` permission
![Screenshot_20240722-211146_Permission controller](https://github.com/user-attachments/assets/cd95b813-c7fc-4431-9a1f-db4d463269e1)

And still I can access the storage for backups, Manga ecc, and that's due to the usage of recent safe api allowing access to specific folders without giving apps permission to access all the files, I recall so.
So, the issue I described is only present in komikku.

**Comment by cuong-tran** [comment]
It depends on the Android OS version. That setting is for Android below 11. Since he can use that feature on SY, he probably needs to do that for Komikku to work the same way as SY. After all, Komikku is forked from SY so no difference here.

On the other hand, from Android 11+, Google limits the usage of accessing other files on the system so no setting for that permission anymore. It requires another approach for that to work. I will implement that for Android 11+ then.
