### ISSUE TITLE
Disable extensions update

### ISSUE THREAD

**Issue by FrankieD777** [komikku-app/komikku#243]
### Describe your suggested feature

Hello!

I hope you are having a good day. I would like to request assistance regarding the configuration of the H integrated into the application. Specifically, I am interested in knowing if it is possible to enable the option to modify said configuration.

I believe there is a small misunderstanding about my intention. I would like to clarify that my goal is to remove the option to update those specific extensions, as I do not want to go through the process of reinstalling everything again.

I appreciate in advance any guidance or help you can offer me on this matter. Also, I want to mention that I currently have no interest in using the custom extensions service that the application offers.

Thank you for taking the time to review and address this request. I look forward to any advice or instructions you can provide.

Thank you again and best regards!

### Other details

And although they have no plans to enable the option to remove the "unofficial" label on other Mihon external repository extensions, I eagerly hope that this feature will be implemented in the near future. This functionality would allow for a smoother and more reliable integration between users and the external resources they wish to use. Moreover, it would resolve many of the issues and mistrust that currently exist due to the "unofficial" label. Without a doubt, improving this area could foster a more robust and collaborative community around Mihon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FrankieD777** [comment]
I don't intend to disable the extensions designed for users over 18; my main goal is to avoid having to update the extensions I have already installed. Every time I try to update, I face the problem that many of these extensions need to be completely reinstalled due to conflicts with the current package. This situation becomes frustrating, especially because I have already configured these extensions according to my preferences and I don't want to invest additional time reinstalling and reconfiguring them every time an update is available. I would like to find a solution that allows me to keep my current extensions in their current state without having to deal with constant reinstalls and conflicts.

**Comment by cuong-tran** [comment]
The reason you still seeing the update notice is because the Komikku's extensions version is higher than Keiyoushi's version. You can go [here](https://komikku-app.github.io/extensions/) to check Komikku's version and go [here](https://keiyoushi.github.io/extensions/) to check for Keiyoushi's version.

Example:
Keiyoushi:
<img width="414" alt="image" src="https://github.com/user-attachments/assets/c9998497-e8b8-47e5-b361-cc71ff25fc0a">
Komikku:
<img width="411" alt="image" src="https://github.com/user-attachments/assets/9e706240-8b05-4856-a166-083ff9623bc2">

Since you installed Keiyoushi's version which is lower, and since Komikku app built-in its repo (it just doesn't show in repo list), that's why app keeps thinking there is an update.

Why Komikku's repo version is higher? Because some extensions (not all) have my own additional changes: more extension features (Elite Babes for example) or better support for Komikku's "Related titles" feature.

You have these options:
1. Switch to Komikku's extensions version for better use. Just uninstall those extensions from Keiyoushi and install Komikku's version. Don't worry about your already configurations because all configurations should be kept after uninstall/reinstall extensions. If you still worry and not sure about configurations being kept, remember that the backup/restore feature also has option to save "Source settings".
2. If you still prefer Keiyoushi's version then wait for the "repo enable/disable" feature to be rolled out on Komikku. With that feature you can disable any repo you want or remove Komikku's built-in repo (hence will no longer conflict or update notice). That feature is already implemented [here](https://github.com/komikku-app/komikku/tree/feature/repo) but waiting for a [bug](https://github.com/mihonapp/mihon/issues/938) to be fixed on Mihon to be released.

**Comment by FrankieD777** [comment]
The reason why you keep seeing the update notice is because the version of the Komikku extensions is higher than that of Keiyoushi. You can check the Komikku version [here](https://komikku-app.github.io/extensions/) and the Keiyoushi version [here.](https://keiyoushi.github.io/extensions/)

Example:
Keiyoushi: 
Komikku: 
<img alt="imagen" width="414" src="https://private-user-images.githubusercontent.com/16017808/356323983-c9998497-e8b8-47e5-b361-cc71ff25fc0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDM5NDksIm5iZiI6MTcyMzIwMzY0OSwicGF0aCI6Ii8xNjAxNzgwOC8zNTYzMjM5ODMtYzk5OTg0OTctZThiOC00N2U1LWIzNjEtY2M3MWZmMjVmYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDExNDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOGYyNTMwY2Q3YTJkYmZlNWUwNTYxMDkxMzkxZWYwZWFiNzUyMmE5ZWIzNGY0OGFiYmY0MzMyOTNmM2U3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82qapzcmvzxV6qreOTxQlVlrV1PFbV6TiNFPDgTYNt8"> 
<img alt="imagen" width="411" src="https://private-user-images.githubusercontent.com/16017808/356324080-9e706240-8b05-4856-a166-083ff9623bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDM5NDksIm5iZiI6MTcyMzIwMzY0OSwicGF0aCI6Ii8xNjAxNzgwOC8zNTYzMjQwODAtOWU3MDYyNDAtOGIwNS00ODU2LWExNjYtMDgzZmY5NjIzYmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDExNDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOWQzZWNhN2FhMzkwZTExMjM5M2EwMGU5MjM2ZjI2OTA2OTQ3ZDEyNTQ1ZGFjMjUzOGUwMGI1YWM5YzYxZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6pCTsAx7OkFXov2wTMbo3b2EhaiDe1ZUiJEwQtIwAtE">

Since you installed the Keiyoushi version, which is lower, and because the Komikku app incorporated its own repository (it just doesn't show up in the list of repositories), that's why the app still thinks there is an update.

Why is the Komikku repository version higher? Because some extensions (not all) have my own additional changes: more extension features (like Elite Babes, for example) or better compatibility with Komikku's "Related Titles" feature.

You have these options:

1. Switch to the Komikku extension version for better use. Simply uninstall those Keiyoushi extensions and install the Komikku version. Don't worry about the settings you already have, as all settings should be retained after uninstalling or reinstalling the extensions. If you are still concerned and not sure that the settings will be retained, remember that the backup or restore function also has the option to save "Source Settings."

2. If you still prefer the Keiyoushi version, wait for the "enable/disable repository" feature to be implemented in Komikku. With that feature, you will be able to disable any repository you want or remove Komikku's built-in repository (therefore, there will no longer be conflicts or update notices). That feature is already implemented [here,](https://github.com/komikku-app/komikku/tree/feature/repo) but we are waiting for a [bug in Mihon](https://github.com/mihonapp/mihon/issues/938) to be fixed.

Thank you so much for your great help, it's already solved! :3 I would also like to apologize for my rude and ignorant behavior in not knowing how the app works. Really, thanks again for your patience and for maintaining a friendly tone, thank you so much.

**Comment by cuong-tran** [comment]
You're welcome.
