### ISSUE TITLE
Enhance duplicate entry detection

### ISSUE THREAD

**Issue by isabella-almeidaa** [komikku-app/komikku#298]
### Describe your suggested feature

Also include alternative names ( located on the description of the manga)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
The alternative title put in manga's description is done by the extension itself. The app can only see the description as a whole text, it can't know which is the alternative title. Without changing how all the extension works, this request can't be implemented.
Since Tachiyomi is down, App & Extension has been split & dev by different persons, so something like this is likely never gonna happen.
