### ISSUE TITLE
Hide Duplicate Sources

### ISSUE THREAD

**Issue by ArchCelestial** [komikku-app/komikku#380]
### Describe your suggested feature

I have both the Komikku and the Keiyoshi repos in Komikku right now; I would like some way to hide the duplicate extensions so that each extension shows up once. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kana-shii** [comment]
Wait for stable version new release. It's already possible to do that on preview

**Comment by cuong-tran** [comment]
Previously on Mihon or other fork, if you add 2 repos with same extensions, they will show only one but not really sure which repo it's from. It will randomly from either of 2 repos. Problem is since extensions' signatures are different, you will end-up unable to update extensions that way.
So currently on preview version, it will now show extensions from each repos separated. You will have option to hide repo (not remove). I'm sorry I won't revert it back to the way it was before.
