### ISSUE TITLE
Added change of font color and classification background according to the manha background color

### ISSUE THREAD

**Issue by OtakuArab** [komikku-app/komikku#66]
### Describe your suggested feature

The background of the font must be colored in the same color as the background color of its text

### Other details

komikku 
![Screenshot_٢٠٢٤٠٦٠٦-١٢٢٤٠٣_Komikku](https://github.com/komikku-app/komikku/assets/161339329/a1dc4f88-6859-408c-84e5-ef6f650d792a)

TachJ2k 
![Screenshot_٢٠٢٤٠٦٠٦_١٢٢٤٣٥](https://github.com/komikku-app/komikku/assets/161339329/b867a3d4-f51f-4d41-a81e-ad285788330b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
> @cuong-tran  can you also add Image based background color in reader.
> 
> ![Bac](https://github.com/komikku-app/komikku/assets/109901807/c2ef5978-0d2f-41d1-af09-a9bc10cb571e)
> 
> Best place will be 
> * Reader
>   * General
>     * Background
>       * Dynamic

I got the same thinking. Will add it on the version after this releasing

**Comment by cuong-tran** [comment]
> I was refering to this inage based background
Yes I understand it. I'm wondering is it will be too distracted?

**Comment by cuong-tran** [comment]
> Make it optional like i mentioned above in Reader setting
> 
> * General
>   
>   * Background
>     
>     * Dynamic

I think the current Auto color for reader is good enough and it's better that way than add a dominant color to page's outside. The reason is, it need to consider the matching color with the edge of each page, not the dominant color inside each page, especially with manga type.

So I don't think I will implement this unless there is a case in which dominant color is better than the auto color. Maybe if you can find an example (and maybe demonstrate it), it will be easier for me to see if it's suitable. If you do, please create another issue or discuss in Discord. I will close this for now.
